### ISSUE TITLE
Annotation completed: 0 variants

### ISSUE THREAD

**Issue by mhelena** [edg1983/GREEN-VARAN#1]
Hello!
Thank you so much for the GREEN-VARAN. I think it will perfect for what I need.
I've ran the test script for the test data using: 

python GREEN-VARAN.py -i test/VCF/GRCh38.test.snpEff.vcf.gz -o test/out/test_standard.vcf --AF_file /PATH/to/gnomad/gnomad.genomes.r3.0.sites.vcf.bgz -b GRCh38 -m annotate -s ReMM -s NCBoost -s LinSight --threads 4  

It is completing the compilation with the final message "Annotation completed: 0 variants written in 0:00:00" and giving no clear error. Do you have any idea why that could be happening?
Thank you very much!

**Comment by edg1983** [comment]
Hi Helena,
Thanks for your interest in the tool!
First of all, note that I've pushed a commit a couple of days ago that would fix an issue with AF annotations when (activated with --allelefreq option). Please download this latest version eventually.

Have you downloaded the score resources in the scores folder? Otherwise, the annotation fails because it cannot find the expected field in the annotation files (obviously since the files are actually not there). I've realized that the tool to not report proper errors for scores missing files, I will fix this in a future release.

There is a script in the resources folder that can be used to download the scores files from zenodo repositories. See also the full documentation for more detailed instructions on how to download and organize the various resources.

**Comment by Manuelaio** [comment]
Dear @edg1983, thanks for your tool.  
How much is the total size of the annotation files in **resources** folder? Running `prepare_resources.sh `was downloading around 190 Gb of files when I stopped it. 
In Zenodo repository, the database is around 7 GB, how do I explain this difference ? 
Thanks in advance.

**Comment by edg1983** [comment]
Hi. 
By default, the script will attempt to download the whole GREEN-DB collection. This includes the database, but also several prediction scores, additional functional regions, and gnomAD files for AF annotation. Thus the total size is much larger. Try using `--list` to get a list of all available files and just download the ones you want using `--name`

I suggest you try also the new version I've pushed in the repository (nim_version), it comes with Nextflow workflow for automatic download and annotation. You clone the nim_version branch. Unfortunately, the documentation is not yet updated. 

If you have Nextflow>=v20.10 you can get a list of available datasets using
`nextflow workflow/download.nf --list_data`

My suggestion is to download just the best scores and the regions needed for prioritization. You can do this using
`nextflow workflow/download.nf --scores best --regions best --db --build GRCh38`

You can eventually add `--AF` if you need also AF annotations and change the `--build` to GRCh37 if you are working with the previous release of the human genome.
Assuming GREEN-VARAN is the tool folder, by default all files are downloaded in GREEN-VARAN/resources/[genome_build], you can adjust this folder by using `--resource_folder`

When you have downloaded the files you can annotate and prioritize your file using the main nextflow workflow. 
If $GREENVARAN is the folder where you have downloaded the tool, you can use something like this
```
nextflow workflow/main.nf \
--scores best --regions best \
--build GRCh38 \
--greenvaran_config $GREENVARAN/config/priotitize_smallvars.json \
--greenvaran_dbschema $GREENVARAN/config/greendb_schema_v2.5.json \
--input input.vcf \
--output output_folder
```
Again you can `--AF` if you also need to annotate for population AF, and use `--resource_folder` in case you downloaded the datasets to a custom location.
By default, the tool expects 2 AF annotation fields in your VCF `gnomAD_AF` and `gnomAD_AF_nfe` and some other fields for regions and scores. These are set by the annotation workflow, but if you are processing a file that has been already annotated you can adjust these by updating the file `$GREENVARAN/config/priotitize_smallvars.json`

**Comment by Manuelaio** [comment]
Thanks for answers. I'm very interested in using your tool for WGS data. 
I cloned your branch however trying **nextflow** option (version 21.10.1.5647) I have the following error: 

` Unable to parse config file: '/workflow/nextflow.config' 
Compile failed for sources FixedSetSources[name='/groovy/script/Script3A6B90BB14E5934DFC24E52DBEE51618']. Cause: org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
  /groovy/script/Script3A6B90BB14E5934DFC24E52DBEE51618: 222: Unexpected input: `

I guess something's wrong in `nextflow.config` file.

**Comment by edg1983** [comment]
Hi! 
Thanks for reporting this! As said, the new version is still in development. I've tracked the issue to a malformed line in the resources description file. 
I've fixed this now, so the nextflow workflow should work now if you clone the latest commit.

My suggestion is to start with a VCF annotated for gene consequences with SnpEff or bcftools and then use the following command (this example is running from the tool folder):
```
nextflow workflow/main.nf -profile local \
--input inputfile.vcf.gz \
--build GRCh38 \
--greenvaran_config config/prioritize_smallvars.json \
--greenvaran_dbschema config/greendb_schema_v2.5.json \
--scores best \
--regions best \
--AF \
--out output_folder 
```
The pipeline will check for files in the resources folder in GREEN-VARAN folder and eventually download missing files.

If your VCF is already annotated with population AF, you can remove `--AF` and adjust the AF fields names in `config/prioritize_smallvars.json` before running.

**Comment by edg1983** [comment]
This refers to the old version, thus I close this one.
