### ISSUE TITLE
=== GNOMAD AF === Cannot get property 'file' on null object

### ISSUE THREAD

**Issue by ghost** [edg1983/GREEN-VARAN#10]
Hi,

I got an error as below when I ran workflow/main.nf. Do you know what has gone wrong.

N E X T F L O W  ~  version 22.10.2
Launching `/proj/sens2023551/wgs_nes/GREEN-VARAN-1.2/workflow/main.nf` [irreverent_swanson] DSL2 - revision: ad29e3fa07
Available datasets. Star indicate corresponding file is available locally
=== SCORES ===
CADD: /proj/sens2023551/wgs_nes/GREEN-VARAN-1.2/resources/GRCh37/GRCh37/GRCh37_CADD.tsv.gz
DANN: /proj/sens2023551/wgs_nes/GREEN-VARAN-1.2/resources/GRCh37/GRCh37/GRCh37_DANN.tsv.gz
Eigen: /proj/sens2023551/wgs_nes/GREEN-VARAN-1.2/resources/GRCh37/GRCh37/GRCh37_Eigen.tsv.gz
ExPECTO: /proj/sens2023551/wgs_nes/GREEN-VARAN-1.2/resources/GRCh37/GRCh37/GRCh37_ExPECTO.tsv.gz
FATHMM_MKLNC: /proj/sens2023551/wgs_nes/GREEN-VARAN-1.2/resources/GRCh37/GRCh37/GRCh37_FATHMM-MKL_NC.tsv.gz
FATHMM_XF: /proj/sens2023551/wgs_nes/GREEN-VARAN-1.2/resources/GRCh37/GRCh37/GRCh37_FATHMM-XF_NC.tsv.gz
FIRE: /proj/sens2023551/wgs_nes/GREEN-VARAN-1.2/resources/GRCh37/GRCh37/GRCh37_FIRE.tsv.gz
GWAVA: /proj/sens2023551/wgs_nes/GREEN-VARAN-1.2/resources/GRCh37/GRCh37/GRCh37_gwava.bed.gz
LinSight: /proj/sens2023551/wgs_nes/GREEN-VARAN-1.2/resources/GRCh37/GRCh37/GRCh37_LinSight.bed.gz
NCBoost: /proj/sens2023551/wgs_nes/GREEN-VARAN-1.2/resources/GRCh37/GRCh37/GRCh37_NCBoost.tsv.gz
ncER: /proj/sens2023551/wgs_nes/GREEN-VARAN-1.2/resources/GRCh37/GRCh37/GRCh37_ncER_perc.bed.gz
PhyloP100: /proj/sens2023551/wgs_nes/GREEN-VARAN-1.2/resources/GRCh37/GRCh37/GRCh37_PhyloP100.bed.gz
ReMM: /proj/sens2023551/wgs_nes/GREEN-VARAN-1.2/resources/GRCh37/GRCh37/GRCh37_ReMM.tsv.gz
=== REGIONS ===
TFBS: /proj/sens2023551/wgs_nes/GREEN-VARAN-1.2/resources/GRCh37/GRCh37/GRCh37_TFBS.merged.bed.gz
DNase: /proj/sens2023551/wgs_nes/GREEN-VARAN-1.2/resources/GRCh37/GRCh37/GRCh37_DNase.merged.bed.gz
UCNE: /proj/sens2023551/wgs_nes/GREEN-VARAN-1.2/resources/GRCh37/GRCh37/GRCh37_UCNE.bed.gz
dbSuper: /proj/sens2023551/wgs_nes/GREEN-VARAN-1.2/resources/GRCh37/GRCh37/GRCh37_dbSuper.bed.gz
=== GNOMAD AF ===
Cannot get property 'file' on null object

**Comment by edg1983** [comment]
This is fixed now in the master branch! Thanks to @JiayangZhou for the quick fix.
