### ISSUE TITLE
test error

### ISSUE THREAD

**Issue by abrusell** [edg1983/GREEN-VARAN#13]
Hi Edoardo,
I've downloaded the binaries and all the GRCh38 files
When I try to run the test I get the following error:
`$ ./greenvaran smallvars -i test/VCF/GRCh38.test.smallvars.vcf.gz -o test/out/test_smallvars.vcf --db resources/GRCh38/GRCh38_GREEN-DB.bed.gz --dbschema config/greendb_schema_v2.5.json --config config/prioritize_smallvars.json --genes test/VCF/genes_list_example.txt 
 / __)(  _ \(  __)(  __)(  ( \ ___ / )( \ / _\ (  _ \ / _\ (  ( \\
( (_ \ )   / ) _)  ) _) /    /(___)\ \/ //    \ )   //    \/    /
 \___/(__\_)(____)(____)\_)__)      \__/ \_/\_/(__\_)\_/\_/\_)__)                    
                                                             
                                              _.-~`  `~-.
                  _.--~~~---,.__          _.,;; .   -=(@'`\\
               .-`              ``~~~~--~~` ';;;       ____)
            _.'            '.              ';;;;;    '`_.'
         .-~;`               `\           ' ';;;;;__.~`
       .' .'          `'.     |           /  /;''
        \/      .---'' ``)   /'-._____.--'\  \\
       _/|    (`        /  /`              `\ \__
',    `/- \   \      __/  (_                /-\-\-`
  `;'-..___)   |     `/-\-\-`
    `-.       .'
 jgs   `~~~~``

[2023-12-18T13:10:55] - INFO: Reading config from file: config/prioritize_smallvars.json
[2023-12-18T13:10:55] - INFO: N selected chromosomes: 25
[2023-12-18T13:10:55] - INFO: N selected genes: 23
[2023-12-18T13:10:55] - INFO: Update existing gene annotations: true
[2023-12-18T13:10:55] - INFO: Filter mode active: false
[2023-12-18T13:10:55] - INFO: === Start processing VCF ===
[2023-12-18T13:10:55] - WARN: gnomAD_AF field defined in config not present in the VCF header
[2023-12-18T13:10:55] - WARN: gnomAD_AF_nfe field defined in config not present in the VCF header
[2023-12-18T13:10:55] - WARN: TFBS field defined in config not present in the VCF header
[2023-12-18T13:10:55] - WARN: DNase field defined in config not present in the VCF header
[2023-12-18T13:10:55] - WARN: UCNE field defined in config not present in the VCF header
[2023-12-18T13:10:55] - WARN: FATHMM_MKLNC field defined in config not present in the VCF header
[2023-12-18T13:10:55] - WARN: ncER field defined in config not present in the VCF header
[2023-12-18T13:10:55] - WARN: ReMM field defined in config not present in the VCF header
[2023-12-18T13:10:55] - WARN: Prioritize is not active and all variants will get level zero
strutils.nim(1159)       parseFloat
Error: unhandled exception: invalid float: FO704657.1 [ValueError]
`

what is going wrong?
Thanks

**Comment by edg1983** [comment]
Hi,

I've tried to reproduce this, but it worked for me using your command. 

I've used the binary from the v1.2 release
`wget https://github.com/edg1983/GREEN-VARAN/releases/download/v1.2/greenvaran`

And the GREEN-DB bed file from Zenodo, as described in the resources folder:
```
wget https://zenodo.org/record/5636209/files/GRCh38_GREEN-DB.bed.gz.csi
wget https://zenodo.org/record/5636209/files/GRCh38_GREEN-DB.bed.gz
```

Have you used the same files in your execution?

**Comment by abrusell** [comment]
Hi,
Yes, I've used exactly the same files.

**Comment by edg1983** [comment]
Based on your error, I suspect something is wrong with your GREEN-DB bed file. It seems like the tool is parsing the wrong column and getting the gene name instead of the number it expects (`FO704657.1` is one of the gene names present in the DB).

I don't get why it's not working for you since it works for me with exactly the same command.

Can you download the bed file and index file again using the links above and then try to run the test with these new files?

**Comment by abrusell** [comment]
Thanks Edoardo, 
I already did it to double check it before my previous reply...

**Comment by abrusell** [comment]
```
$ zcat resources/GRCh38/GRCh38_GREEN-DB.bed.gz | head
#Chromosome	Start	End	regionID	std_type	db_source	constrain_pct	PhyloP100_median	closestGene_symbol	closestGene_dist	closestProt_symbol	closestProt_dist	controlled_genes	N_methods
chr1	10000	10600	0_enh	enhancer	DECRES	NA	NA	MIR6859-1	6770	OR4F5	54820		1
chr1	10244	10357	502_pro	promoter	BENGI	NA	NA	MIR6859-1	7013	OR4F5	55063		0
chr1	10400	11201	631_pro	promoter	EnsemblRegBuild	NA	0.061	MIR6859-1	6169	OR4F5	54219		1
chr1	10433	10559	663_pro	promoter	BENGI	NA	NA	MIR6859-1	6811	OR4F5	54861		0
chr1	11537	12337	8605_enh	enhancer	ENCODE-HMM	NA	0.025	MIR6859-1	5033	OR4F5	53083		1
chr1	13137	15137	13323_enh	enhancer	ENCODE-HMM	NA	-0.031	MIR6859-1	2233	OR4F5	50283	RP11-34P13.13,RP11-206L10.2,AP006222.2	1
chr1	18137	22137	38399_enh	enhancer	ENCODE-HMM	NA	-0.0675	MIR6859-1	702	OR4F5	43283		1
chr1	20000	20200	47644_enh	enhancer	DECRES	NA	0.091	MIR6859-1	2565	OR4F5	45220		1
chr1	22801	23000	67550_enh	enhancer	EnsemblRegBuild	NA	0.0225	MIR6859-1	5366	OR4F5	42420		1

```

**Comment by edg1983** [comment]
It's weird. The file I downloaded with the link above 
`wget https://zenodo.org/record/5636209/files/GRCh38_GREEN-DB.bed.gz`

looks different from yours. The header cols are:

```
#chromosome
start
stop
regionID
std_type
DB_source
N_sources
N_methods
constrain_pct
PhyloP100_median
closestGene_symbol
closestGene_dist
closestProt_symbol
closestProt_dist
closestGene_TSS_symbol
closestGene_TSS_dist
closestProt_TSS_symbol
closestProt_TSS_dist
controlled_genes
N_controlled_genes
```

Are you sure you are using the same file and not a previous version?

**Comment by abrusell** [comment]
Ok, 
downloaded again the files and now it' magically working...
I don't really know what happened
Thank you!
