### ISSUE TITLE
Access to undefined parameter

### ISSUE THREAD

**Issue by salhajh** [edg1983/GREEN-VARAN#14]
Dear Edoardo,

I have been attempting to run the Nextflow workflow on a VCF file (and on the test file provided within the package), however regardless of version of nextflow (I have used both v20.10.0 and 23.04.3), I receive the following errors:

> WARN: Access to undefined parameter `annotations` -- Initialise it to a default value eg. `params.annotations = some_value`
> Cannot get property 'GRCh38' on null object

I am not sure where I need to amend the code to fix this issue (I have used the same code given in the example workflow) and did check one of the other issues raised on gitHub, however the provided command on the "workflow green_varan failed #8" issue thread did not run for me either.

I would appreciate any support with this matter.

Thank you,
Safaa

**Comment by edg1983** [comment]
Hi,

All annotations are defined in the config/resources.conf file in the workflow folder. This file is imported automatically from the main configuration file (nextflow.config). Thus, it is strange that this is not imported correctly for you.

What command are you using exactly when you get this error? I'll try to replicate your issue to understand what's going on.

**Comment by salhajh** [comment]
Thank you for your quick response!

I do have that file in my folder and it seems to match the contents of the file in the github workflow folder. I am not sure if the script is not recognising to use that file? My command is (taken from the example):

nextflow workflow/main.nf -profile local --input test450-101/smallvarsMorf.test.vcf.gz --out test450-101/workflow --build GRCh38 --scores best --regions best --AF --greenvaran_config config/prioritize_smallvars.json     --greenvaran_dbschema config/greendb_schema_v2.5.json

Thank you.

**Comment by edg1983** [comment]
Hi,

I've tested this locally and it's working fine for me using your same command from the tool folder.
Have you cloned the entire repository?

By default, the Nextflow pipeline expects the resources.conf file to be in the config subfolder of the workflow folder (essentially where the main.nf file is).

To clarify, you must have a folder structure like this:

```bash
workflow
|-- bin
|   |-- bgzip
|   |-- greenvaran
|   |-- tabix
|   `-- vcfanno
|-- config
|   `-- resources.conf
|-- download.nf
|-- main.nf
|-- modules
|   |-- annotate.nf
|   `-- utils.nf
|-- nextflow.config
`-- README.md
```

Then assuming the `workflow` folder is in /opt/GREEN-VARAN, a command like this should work:

```bash
export GV_DIR='/opt/GREEN-VARAN'
nextflow ${GV_DIR}/workflow/main.nf -profile local --input test450-101/smallvarsMorf.test.vcf.gz --out test450-101/workflow --build GRCh38 --scores best --regions best --AF --greenvaran_config ${GV_DIR}/config/prioritize_smallvars.json --greenvaran_dbschema ${GV_DIR}/config/greendb_schema_v2.5.json
```

**Comment by salhajh** [comment]
Dear Edoardo,

Apologies for the late response, and thank you for your help! I was able to download the annotation files and the pipeline is now functioning as required.

Thank you once again!
Safaa
