### ISSUE TITLE
GRCh38 resources needed for GRCh37 annotation

### ISSUE THREAD

**Issue by ljohansson** [edg1983/GREEN-VARAN#5]
Dear Eduardo, 

I started a new issue, because I believe it is not related to our earlier discussion. I am now using the Green-varan workflow configuration. While analyzing data from build GRCh37, having the all scores and regions on, the program wants to annotate the vcf file using GRCh38 recources. 

Can you advise? See the error message below.

N E X T F L O W  ~  version 21.10.6
Launching `./GREEN-VARAN/workflow/main.nf` [lethal_majorana] - revision: 539422f1a2
==============================================
GREEN-VARAN annotation - N F   P I P E L I N E
==============================================
input file          : ./XX.vcf.gz
build               : GRCh37
output              : ./results
greenvaran config   : ./GREEN-VARAN//config/prioritize_smallvars.json
greenvaran dbschema : ./GREEN-VARAN//config/greendb_schema_v2.5.json
resource folder     : ./GREEN-VARAN/workflow/../resources

ACTIVE ANNOTATIONS:
    Scores          : all
    Regions         : all
    AF              : true
==============================================

WARN: Nextflow version 21.10.6 does not match workflow required version: 20.10.0 -- Execution will continue, but things may break!
[-        ] process > WRITE_SCORE_TOML -

[-        ] process > WRITE_SCORE_TOML      -
[-        ] process > DOWNLOAD_REGION       -
[-        ] process > WRITE_REGION_TOML     -
[-        ] process > WRITE_AF_TOML         -
[-        ] process > concat_toml           -
[-        ] process > ANNOTATE:annotate_vcf -
[-        ] process > ANNOTATE:index_vcf    -
[-        ] process > green_varan           -
TAD not found at ./GREEN-VARAN/resources/GRCh37/GRCh38_TAD.bed.gz

In addition: A possible cause is that the GRCh37 TAD bed file was missing from my folder. There is an issue with downloading the file and they seem to be missing from the download server. In addition two other files could not be downloaded.
GRCh37_dbSuper | regions | https://zenodo.org/record/5705936/files/GGRCh37_dbSuper.bed.gz.csi
GRCh37_TAD | regions | https://zenodo.org/record/5705936/files/GRCh37_TAD.bed.gz
GRCh37_TAD | regions | https://zenodo.org/record/5705936/files/GRCh37_TAD.bed.gz.csi

**Comment by edg1983** [comment]
There was a typo in the file describing the sources for GRCh37 annotations for TAD domains. I've just pushed a fix, so clone the repo again and it should be OK.

See my answers on issue #3  for a possible solution to run the annotation workflow with your file without chr prefix.

**Comment by ljohansson** [comment]
Dear Edoardo,
Indeed the issue with the TAD domains error has been resolved. However, an empty vcf file is returned when using the all scores and all regions option, while all seems to work well with the best options. No errors are reported when using the 'all' settings.

This is the command when using the best options.

nextflow $GREENVARANFOLDER/workflow/main.nf \
    -profile local \
    --input $VCFTOANNOTATE \
    --build GRCh37 \
    --out $OUTPUTFOLDER/results2 \
    --scores best \
    --regions best \
    --AF \
    --greenvaran_config $GREENVARANFOLDER/config/prioritize_smallvars.json \
    --greenvaran_dbschema $GREENVARANFOLDER/config/greendb_schema_v2.5.json \
    --greenvaran_options '--chrom 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,X,Y'


This is the command when using the all options.

nextflow $GREENVARANFOLDER/workflow/main.nf \
    -profile local \
    --input $VCFTOANNOTATE \
    --build GRCh37 \
    --out $OUTPUTFOLDER/results_complete \
    --scores all \
    --regions all \
    --AF \
    --greenvaran_config $GREENVARANFOLDER/config/prioritize_smallvars.json \
    --greenvaran_dbschema $GREENVARANFOLDER/config/greendb_schema_v2.5.json \
    --greenvaran_options '--chrom 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,X,Y'

This is the top of the log for the best options.

[2022-03-29T17:55:26] - INFO: Reading config from file: prioritize_smallvars.json
[2022-03-29T17:55:26] - DEBUG: af:@["gnomAD_AF", "gnomAD_AF_nfe"]
[2022-03-29T17:55:26] - DEBUG: maxaf:0.009999999776482582
[2022-03-29T17:55:26] - DEBUG: regions:@["TFBS", "DNase", "UCNE"]
[2022-03-29T17:55:26] - DEBUG: scores:{"FATHMM_MKLNC": 0.9079999923706055, "ncER": 98.59999847412109, "ReMM": 0.9629999995231628}
[2022-03-29T17:55:26] - DEBUG: constraint:0.699999988079071
[2022-03-29T17:55:26] - DEBUG: more_regions:@[]
[2022-03-29T17:55:26] - DEBUG: more_values:{:}
[2022-03-29T17:55:26] - INFO: N selected chromosomes: 24
[2022-03-29T17:55:26] - INFO: N selected genes: 0
[2022-03-29T17:55:26] - DEBUG: Selected chromosomes: @["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "X", "Y"]
[2022-03-29T17:55:26] - DEBUG: Selected genes: {}
[2022-03-29T17:55:26] - INFO: Update existing gene annotations: true
[2022-03-29T17:55:26] - INFO: Filter mode active: false
[2022-03-29T17:55:26] - INFO: === Start processing VCF ===
[2022-03-29T17:55:26] - WARN: No ANN or BCSQ field detected in header so ANN will be created
[2022-03-29T17:55:26] - DEBUG: Processing chromosome 1
[2022-03-29T17:55:45] - INFO: 10000 vars analyzed, last batch in 0.0 min 19.09 sec

And the top of the log for the all options

[2022-04-01T11:04:31] - INFO: Reading config from file: prioritize_smallvars.json
[2022-04-01T11:04:31] - DEBUG: af:@["gnomAD_AF", "gnomAD_AF_nfe"]
[2022-04-01T11:04:31] - DEBUG: maxaf:0.009999999776482582
[2022-04-01T11:04:31] - DEBUG: regions:@["TFBS", "DNase", "UCNE"]
[2022-04-01T11:04:31] - DEBUG: scores:{"FATHMM_MKLNC": 0.9079999923706055, "ncER": 98.59999847412109, "ReMM": 0.9629999995231628}
[2022-04-01T11:04:31] - DEBUG: constraint:0.699999988079071
[2022-04-01T11:04:31] - DEBUG: more_regions:@[]
[2022-04-01T11:04:31] - DEBUG: more_values:{:}
[2022-04-01T11:04:31] - INFO: N selected chromosomes: 24
[2022-04-01T11:04:31] - INFO: N selected genes: 0
[2022-04-01T11:04:31] - DEBUG: Selected chromosomes: @["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "X", "Y"]
[2022-04-01T11:04:31] - DEBUG: Selected genes: {}
[2022-04-01T11:04:31] - INFO: Update existing gene annotations: true
[2022-04-01T11:04:31] - INFO: Filter mode active: false
[2022-04-01T11:04:31] - INFO: === Start processing VCF ===
[2022-04-01T11:04:31] - WARN: No ANN or BCSQ field detected in header so ANN will be created
[2022-04-01T11:04:31] - DEBUG: Processing chromosome 1
[2022-04-01T11:04:31] - DEBUG: chromosome 1: 0 processed; 0 annotated, 0 vars of interest, 0 written

All seems identical, except for the best options doing annotation and the all option not adding annotations. Do you have an idea what is going wrong?

Regards,
Lennart

**Comment by edg1983** [comment]
Hi,

I think there is still some issue in the annotation process before green-varan, probably one of the sources is not configured properly.
The pipeline should generate a `.toml` file in the output folder. Can you inspect this and check the path of the annotation files are all correct?

I will do a test myself in the next few days and let you know

**Comment by edg1983** [comment]
Using the `.toml` file generated in the output folder when using `--scoees all` and `--regions all`, you may try to annotate the input file and look at the output of vcfanno. I assume that there is something wrong in the annotation step so this may help clarify the issue.
You can use a command like this and let me know if you see any error in the output

```
GOGC=2000 IRELATE_MAX_CHUNK=10000 IRELATE_MAX_GAP=1000 \
workflow/bin/vcfanno -p 10 tomlfile.toml test/VCF/GRCh38.test.smallvars.vcf.gz \
| bgzip -c > annotated.tmp.vcf.gz
```

Adjust `-p` to reflect the number of threads available on your system.

**Comment by ljohansson** [comment]
Indeed there is an annotations.toml file in the output directory. When I use the command with the appropriate input files (GRCh37) I get the following error regarding the Header of the TAD bed file. I have compared with the GRCh38 TAD bed file and the header seems identical. 

=============================================
vcfanno version 0.3.2 [built with go1.12.1]

see: https://github.com/brentp/vcfanno
=============================================
vcfanno.go:115: found 25 sources from 19 files
vcfanno.go:156: falling back to non-bgzip
api.go:811: WARNING: using op 'self' when with Number='1' for '' from '/groups/./GREEN-VARAN/workflow/../resources/GRCh37/GRCh37_TADs.bed.gz' can result in out-of-order values when the query is multi-allelic
api.go:812:        : this is not an issue if the query has been decomposed.
vcfanno.go:38: using IRELATE_MAX_GAP of 1000
vcfanno.go:38: using IRELATE_MAX_CHUNK of 10000
parallel.go:151: bix: error creating chunked reader from /groups/./GREEN-VARAN/workflow/../resources/GRCh37/GRCh37_TADs.bed.gz: gzip: invalid header


This is the header of the TAD bed file obtained from here: https://zenodo.org/record/5705936#.Yk_35ugzY2x
[ljohansson@fender results_complete]$ zcat /groups/./GREEN-VARAN/workflow/../resources/GRCh37/GRCh37_TADs.bed.gz | head
#CHROM  START   END     CELL_LINE       METHOD  DETECTION       TAD_id
chr1    50000   1240000 GM12878 HiChIP  DI      TAD_1
chr1    75000   3825000 IMR90   HiC     GMAP    TAD_2
chr1    250000  500000  GM12878 HiChIP  DI      TAD_3
chr1    500000  800000  GM12878 HiChIP  DI      TAD_4
chr1    535000  1845000 HUVEC   HiC     GMAP    TAD_5

**Comment by edg1983** [comment]
I've pushed a new release that fix this issue. The tool now have a `--nochr` option that can be used to correctly process input VCF when no `chr` prefix is present. 
Let me know if it works as expected for you and I will close this issue

**Comment by ljohansson** [comment]
I'm currently installing the new tool, however I got an error with the nim_compile.sh

FATAL:   Unable to handle docker://brentp/musl-hts-nim:latestf uri: failed to get checksum for docker://brentp/musl-hts-nim:latestf: Error reading manifest latestf in docker.io/brentp/musl-hts-nim: manifest unknown: manifest unknown


I was able to run the script by removing the f in latestf in this line:
docker://brentp/musl-hts-nim:latestf \
Is this correct?

**Comment by edg1983** [comment]
Yes. It looks like a typo in the .sh script.

Anyway, you can use the pre-compiled binaries in the release and you would
not need to compile from source.

Binaries are also included in the workflow, so the nextflow pipeline should
work as well out of the box without compiling

Edoardo

**Comment by ljohansson** [comment]
Unfortunately I did not get results with the --nochr yet.
Should it be the --nochr option directly or --greenvaran_options '--nochr' ?

**Comment by edg1983** [comment]
Hi, At the moment when you are using the nextflow workflow you should use 
`--greenvaran_options '--nochr'` 
to pass the additional `--chr` option to GREEN-VARAN. 

But you are right, it would probably be better to have this option directly in the main params of nextflow.

**Comment by edg1983** [comment]
I assume the new `--nochr` option solved this. Feel free to reopen if necessary
