### ISSUE TITLE
confused with the annotated results

### ISSUE THREAD

**Issue by LIKUOKUO** [edg1983/GREEN-VARAN#7]
I was confused with the annotated results, here is the example which labled as greendb_level=3. But I don't know which three levels satisfy threshold. Was these three levels: MAF<1%; overlap with DNase andTFBS; greendb_constraint=0.722409>0.7. The ReMM=0.538 and ncER=85.5791 were not satisfy FDR50 threshold?
Thank you for your kindly help.

AC=1;AF=0.5;AN=2;BaseQRankSum=0.12;ClippingRankSum=-0;DP=9;ExcessHet=3.0103;FS=7.782;MLEAC=1;MLEAF=0.5;MQ=60;MQRankSum=-0;QD=10.64;ReadPosRankSum=-0;SOR=3.611;VQSLOD=22.3209;culprit=MQ;FATHMM_MKLNC=0.1036;ReMM=0.538;ncER=85.5791;DNase;TFBS;gnomAD_AF=0.005553;gnomAD_AF_afr=0.0053394;gnomAD_AF_amr=0.0048544;gnomAD_AF_nfe=0.0046707;greendb_id=561490_pro,2_biv,505745_pro;greendb_stdtype=bivalent,promoter;greendb_dbsource=FOCS,SegWey,ENCODE-HMM,BENGI,EnsemblRegBuild,FANTOM5;greendb_genes=RBP7;greendb_constraint=0.722409;greendb_level=3;ANN=C|promoter|MODIFIER|RBP7||||||||||||,C|bivalent|MODIFIER|RBP7||||||||||||

**Comment by edg1983** [comment]
Hi,
It looks correct. The final level is the sum of supporting evidence as configured in the JSON file. If you are using the default config file these criteria are 
- gnomAD AF < 0.01
- overlap with one of TFBS, DNase or UCNE
- one of ReMM, FATHMM or ncER above FDR50 threshold
- region constraint > 0.7.

In this case your variant satisfy 3 of these 4 criteria (gnomAD AD 0.0055, TFBS+DNase, constraint 0.722) and thus the resulting GREEN-DB level is 3.

You can always modify this behaviour by editing the configuration in the JSON file.

Hope this clarify the annotation procedure.

**Comment by edg1983** [comment]
Please have a look at the new version 1.2. 
In the new version, you can switch between pileup of evidence (as described by my previous comment) and levels mode, which reproduce precisely the mechanism described in the paper (which is essentially a hierarchical passing of the four criteria)
